### ISSUE TITLE
Unable to build project. Error: unable to parse file iottestware.coap.tpd

### ISSUE THREAD

**Issue by dkalashnik** [eclipse/iottestware.coap#1]
Hi
I have followed quick start guide and faced the issue with running command `python /home/titan/iottestware/install.py -p coap -b --path /home/titan/Titan`

```
I/O warning : failed to load external entity "/home/titan/Titan/IoT-Testware/iottestware.coap/iottestware.coap.tpd"
Error: unable to parse file "/home/titan/Titan/IoT-Testware/iottestware.coap/iottestware.coap.tpd"
munmap_chunk(): invalid pointer
```

Full log:
```
root@a770e74d0df9:/home/titan# python /home/titan/iottestware/install.py -p coap -b --path /home/titan/Titan
Getting dependencies ...
 IoT-Testware ... done!
/home/titan/Titan/TestPorts/Common_Components/Socket_API_CNL113686/ already exists
Fetching origin
/home/titan/Titan/TestPorts/IPL4asp/ already exists
Fetching origin
 Test ports ... done!
/home/titan/Titan/ProtocolModules/COMMON/ already exists
Fetching origin
 Protocol modules ... done!
/home/titan/Titan/Libraries/TCCUsefulFunctions_CNL113472/ already exists
Fetching origin
 Libraries ... done!
Getting Dependencies done!
Preparing workspace ...
 Bin directory clean!
Building the project ...
I/O warning : failed to load external entity "/home/titan/Titan/IoT-Testware/iottestware.coap/iottestware.coap.tpd"
Error: unable to parse file "/home/titan/Titan/IoT-Testware/iottestware.coap/iottestware.coap.tpd"
munmap_chunk(): invalid pointer
Aborted (core dumped)
Makefile generated!
make: *** No rule to make target 'compile'.  Stop.
make: *** No targets specified and no makefile found.  Stop.
Compilation done!
Building the project done!
```

Version: 
root@a770e74d0df9:/home/titan/Titan/IoT-Testware/iottestware.coap# git show
commit b88e2532b9f93ec3c9cab6b8774a5d0d0775be42 (HEAD -> master, origin/master, origin/HEAD)
Author: Sascha Hackel <kretzschi@users.noreply.github.com>
Date:   Fri Dec 20 12:29:38 2019 +0100

    Fix dead links and add versioning section

**Comment by alexanderkaiser** [comment]
Hello @dkalashnik,

I really appreciate your interest in the IoT-Testware and regret that the installation process is a bit cumbersome and unfortunately sometimes a bit laborious and error-prone. 

I have just re-enacted your approach and could not reproduce the error. However, this only means that the _iottestware.coap.tpd_ file (which seems to cause the error in this case) is still okay and should be theoretically working. 
Nevertheless, as far as I remember we have already experienced similar issues.

`munmap_chunk(): invalid pointer
Aborted (core dumped)`
I assume this error is thrown by **ttcn3_makefilegen** which is part of Eclipse Titan.
I will investigate and try to find a solution. In the meanwhile, I'd kindly ask you to try the following steps:

As the step of fetching required test ports and protocol modules from GitHub seemed to work, you should already have all required code under `/home/titan/Titan`.
At this point, you might try to use **ttcn3_makefilegen** directly to build Makefile:
`cd /home/titan/Titan/IoT-Testware/iottestware.coap/`
`ttcn3_makefilegen -f -g -m -t iottestware.coap.tpd -e CoAP_TS`
Did this generate a `/home/titan/Titan/IoT-Testware/iottestware.coap/bin/Makefile`?

If not, we will need to dive in a little deeper:
1. Do you still get the same error? (`munmap_chunk(): invalid pointer`)
2. Which version of Titan/ttcn3_makefilegen do you use? `ttcn3_makefilegen -v`

**Comment by dkalashnik** [comment]
Hi @alexanderkaiser thank you for the reply. 

I am using eclipsetitan/titan-ubuntu:6.4.0 conrainer.
When I started installation once again in a manual mode from the last layer it disappears. Then I cleaned previous layers and it successfully built. 

Not sure what is the origin of initial issue, but looks like there is nothing to debug.

**Comment by alexanderkaiser** [comment]
The codebase for [install.py](https://github.com/eclipse/iottestware/blob/master/install.py) might have needed an update for quite some time.

We rely on the folder structure of the Eclipse Titan and the plug-ins. When assembling the dependencies with the Python script, errors and strange constellations may occur. Judging by your last description, I suspect you found exactly such a scenario.

Please report us if you find the cause or solution. We will be grateful to you
